# Generated by Django 2.2.5 on 2020-04-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookInfo',
        ),
    ]
