# Generated by Django 2.2.5 on 2020-05-25 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodsvisitcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsspecification',
            old_name='goods',
            new_name='spu',
        ),
    ]
