# Generated by Django 2.2.5 on 2020-05-25 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20200525_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsspecification',
            name='spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='goods.Goods', verbose_name='商品'),
        ),
    ]
